// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: quiz_attempts.
// - Entity ID: 102019b89b1275676b9986d68e0f1a9a3f8.
// - Entity Version: 102019b8b5a5c89707ba4faf28a57fbb8d2.
// - Task ID: 695af84d032b09907ce19394.
// - Task Root ID: 695a8ab93c0e72020feb5a35.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for QuizAttemptsModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface QuizAttemptsModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  video_id: string;
  question_id: string;
  user_answer: string;
  is_correct: boolean;
  ai_feedback?: string | null;
  attempted_at: string;
}

/**
 * ORM class for QuizAttempts entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class QuizAttemptsORM {
  private static instance: QuizAttemptsORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b89b1275676b9986d68e0f1a9a3f8';
    this.entityName = 'quiz_attempts';
    this.entityVersion = '102019b8b5a5c89707ba4faf28a57fbb8d2';
    this.taskId = '695af84d032b09907ce19394';
    this.taskRootId = '695a8ab93c0e72020feb5a35';
  }

  /**
   * Get singleton instance of QuizAttemptsORM
   */
  public static getInstance(): QuizAttemptsORM {
    if (!QuizAttemptsORM.instance) {
      QuizAttemptsORM.instance = new QuizAttemptsORM();
    }
    
    return QuizAttemptsORM.instance;
  }

  /**
   * Get quiz_attempts by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getQuizAttemptsByIDs(ids: string[]): Promise<QuizAttemptsModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete quiz_attempts by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteQuizAttemptsByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all QuizAttempts records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllQuizAttempts(): Promise<QuizAttemptsModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new QuizAttempts record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertQuizAttempts(data: QuizAttemptsModel[]): Promise<QuizAttemptsModel[]> {
    const structured = data.map((item) => CreateData(QuizAttemptsModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all QuizAttempts records
   */
  async purgeAllQuizAttempts(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List QuizAttempts records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listQuizAttempts(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[QuizAttemptsModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get quiz_attempts by Id index
   * This function gets data by index.
   */
  async getQuizAttemptsById(
    id: string,
  ): Promise<QuizAttemptsModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) quiz_attempts by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuizAttemptsById(
    id: string,
    data: QuizAttemptsModel
  ): Promise<QuizAttemptsModel[]> {
    const index = createIndexId(
      id
    );

    const values = QuizAttemptsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete quiz_attempts by Id index
   */
  async deleteQuizAttemptsById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get quiz_attempts by DataCreator index
   * This function gets data by index.
   */
  async getQuizAttemptsByDataCreator(
    data_creator: string,
  ): Promise<QuizAttemptsModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) quiz_attempts by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuizAttemptsByDataCreator(
    data_creator: string,
    data: QuizAttemptsModel
  ): Promise<QuizAttemptsModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = QuizAttemptsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete quiz_attempts by DataCreator index
   */
  async deleteQuizAttemptsByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get quiz_attempts by DataUpdater index
   * This function gets data by index.
   */
  async getQuizAttemptsByDataUpdater(
    data_updater: string,
  ): Promise<QuizAttemptsModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) quiz_attempts by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuizAttemptsByDataUpdater(
    data_updater: string,
    data: QuizAttemptsModel
  ): Promise<QuizAttemptsModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = QuizAttemptsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete quiz_attempts by DataUpdater index
   */
  async deleteQuizAttemptsByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get quiz_attempts by UserId index
   * This function gets data by index.
   */
  async getQuizAttemptsByUserId(
    user_id: string,
  ): Promise<QuizAttemptsModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) quiz_attempts by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuizAttemptsByUserId(
    user_id: string,
    data: QuizAttemptsModel
  ): Promise<QuizAttemptsModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = QuizAttemptsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete quiz_attempts by UserId index
   */
  async deleteQuizAttemptsByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get quiz_attempts by VideoId index
   * This function gets data by index.
   */
  async getQuizAttemptsByVideoId(
    video_id: string,
  ): Promise<QuizAttemptsModel[]> {
    const index = createIndexVideoId(
      video_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) quiz_attempts by VideoId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuizAttemptsByVideoId(
    video_id: string,
    data: QuizAttemptsModel
  ): Promise<QuizAttemptsModel[]> {
    const index = createIndexVideoId(
      video_id
    );

    const values = QuizAttemptsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete quiz_attempts by VideoId index
   */
  async deleteQuizAttemptsByVideoId(
    video_id: string
  ): Promise<void> {
    const index = createIndexVideoId(
      video_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get quiz_attempts by QuestionId index
   * This function gets data by index.
   */
  async getQuizAttemptsByQuestionId(
    question_id: string,
  ): Promise<QuizAttemptsModel[]> {
    const index = createIndexQuestionId(
      question_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) quiz_attempts by QuestionId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuizAttemptsByQuestionId(
    question_id: string,
    data: QuizAttemptsModel
  ): Promise<QuizAttemptsModel[]> {
    const index = createIndexQuestionId(
      question_id
    );

    const values = QuizAttemptsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete quiz_attempts by QuestionId index
   */
  async deleteQuizAttemptsByQuestionId(
    question_id: string
  ): Promise<void> {
    const index = createIndexQuestionId(
      question_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to QuizAttemptsModel data array
   */
  private resultToData(values: Data[]): QuizAttemptsModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return QuizAttemptsModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as QuizAttemptsModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized QuizAttemptsModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is QuizAttemptsModel => item !== null);
  }
}

/**
 * Convert QuizAttemptsModel data to Value array
 */
function QuizAttemptsModelToValues(data: QuizAttemptsModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'video_id', type: DataType.string, defaultValue: '' },
    { key: 'question_id', type: DataType.string, defaultValue: '' },
    { key: 'user_answer', type: DataType.string, defaultValue: '' },
    { key: 'is_correct', type: DataType.boolean, defaultValue: false },
    { key: 'ai_feedback', type: DataType.string, defaultValue: null },
    { key: 'attempted_at', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof QuizAttemptsModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to QuizAttemptsModel data
 */
function QuizAttemptsModelFromValues(values: Value[]): QuizAttemptsModel {
  const data: Partial<QuizAttemptsModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'video_id':
        data.video_id = ParseValue(value, DataType.string) as string;
        break;
      case 'question_id':
        data.question_id = ParseValue(value, DataType.string) as string;
        break;
      case 'user_answer':
        data.user_answer = ParseValue(value, DataType.string) as string;
        break;
      case 'is_correct':
        data.is_correct = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'ai_feedback':
        data.ai_feedback = ParseValue(value, DataType.string) as string | null;
        break;
      case 'attempted_at':
        data.attempted_at = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as QuizAttemptsModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for VideoId fields
 */
function createIndexVideoId(
  video_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, video_id, 'video_id'),
  ];

  return {
    fields: ['video_id'],
    values
  };
}
/**
 * Create index for QuestionId fields
 */
function createIndexQuestionId(
  question_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, question_id, 'question_id'),
  ];

  return {
    fields: ['question_id'],
    values
  };
}

export default QuizAttemptsORM;