// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: training_sessions.
// - Entity ID: 102019b89b12756730da263a1a57016ade5.
// - Entity Version: 102019b8b5a5c89707ba4faf28a57fbb8d2.
// - Task ID: 695af84d032b09907ce19394.
// - Task Root ID: 695a8ab93c0e72020feb5a35.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for TrainingSessionsModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface TrainingSessionsModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  video_id: string;
  pass_threshold: number;
  total_questions: number;
  is_active: boolean;
  verification_code?: string | null;
}

/**
 * ORM class for TrainingSessions entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class TrainingSessionsORM {
  private static instance: TrainingSessionsORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b89b12756730da263a1a57016ade5';
    this.entityName = 'training_sessions';
    this.entityVersion = '102019b8b5a5c89707ba4faf28a57fbb8d2';
    this.taskId = '695af84d032b09907ce19394';
    this.taskRootId = '695a8ab93c0e72020feb5a35';
  }

  /**
   * Get singleton instance of TrainingSessionsORM
   */
  public static getInstance(): TrainingSessionsORM {
    if (!TrainingSessionsORM.instance) {
      TrainingSessionsORM.instance = new TrainingSessionsORM();
    }
    
    return TrainingSessionsORM.instance;
  }

  /**
   * Get training_sessions by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getTrainingSessionsByIDs(ids: string[]): Promise<TrainingSessionsModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete training_sessions by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteTrainingSessionsByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all TrainingSessions records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllTrainingSessions(): Promise<TrainingSessionsModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new TrainingSessions record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertTrainingSessions(data: TrainingSessionsModel[]): Promise<TrainingSessionsModel[]> {
    const structured = data.map((item) => CreateData(TrainingSessionsModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all TrainingSessions records
   */
  async purgeAllTrainingSessions(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List TrainingSessions records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listTrainingSessions(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[TrainingSessionsModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get training_sessions by Id index
   * This function gets data by index.
   */
  async getTrainingSessionsById(
    id: string,
  ): Promise<TrainingSessionsModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) training_sessions by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTrainingSessionsById(
    id: string,
    data: TrainingSessionsModel
  ): Promise<TrainingSessionsModel[]> {
    const index = createIndexId(
      id
    );

    const values = TrainingSessionsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete training_sessions by Id index
   */
  async deleteTrainingSessionsById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get training_sessions by DataCreator index
   * This function gets data by index.
   */
  async getTrainingSessionsByDataCreator(
    data_creator: string,
  ): Promise<TrainingSessionsModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) training_sessions by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTrainingSessionsByDataCreator(
    data_creator: string,
    data: TrainingSessionsModel
  ): Promise<TrainingSessionsModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = TrainingSessionsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete training_sessions by DataCreator index
   */
  async deleteTrainingSessionsByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get training_sessions by DataUpdater index
   * This function gets data by index.
   */
  async getTrainingSessionsByDataUpdater(
    data_updater: string,
  ): Promise<TrainingSessionsModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) training_sessions by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTrainingSessionsByDataUpdater(
    data_updater: string,
    data: TrainingSessionsModel
  ): Promise<TrainingSessionsModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = TrainingSessionsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete training_sessions by DataUpdater index
   */
  async deleteTrainingSessionsByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get training_sessions by VideoId index
   * This function gets data by index.
   */
  async getTrainingSessionsByVideoId(
    video_id: string,
  ): Promise<TrainingSessionsModel[]> {
    const index = createIndexVideoId(
      video_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) training_sessions by VideoId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTrainingSessionsByVideoId(
    video_id: string,
    data: TrainingSessionsModel
  ): Promise<TrainingSessionsModel[]> {
    const index = createIndexVideoId(
      video_id
    );

    const values = TrainingSessionsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete training_sessions by VideoId index
   */
  async deleteTrainingSessionsByVideoId(
    video_id: string
  ): Promise<void> {
    const index = createIndexVideoId(
      video_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to TrainingSessionsModel data array
   */
  private resultToData(values: Data[]): TrainingSessionsModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return TrainingSessionsModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as TrainingSessionsModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized TrainingSessionsModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is TrainingSessionsModel => item !== null);
  }
}

/**
 * Convert TrainingSessionsModel data to Value array
 */
function TrainingSessionsModelToValues(data: TrainingSessionsModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'video_id', type: DataType.string, defaultValue: '' },
    { key: 'pass_threshold', type: DataType.number, defaultValue: 0 },
    { key: 'total_questions', type: DataType.number, defaultValue: 0 },
    { key: 'is_active', type: DataType.boolean, defaultValue: false },
    { key: 'verification_code', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof TrainingSessionsModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to TrainingSessionsModel data
 */
function TrainingSessionsModelFromValues(values: Value[]): TrainingSessionsModel {
  const data: Partial<TrainingSessionsModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'video_id':
        data.video_id = ParseValue(value, DataType.string) as string;
        break;
      case 'pass_threshold':
        data.pass_threshold = ParseValue(value, DataType.number) as number;
        break;
      case 'total_questions':
        data.total_questions = ParseValue(value, DataType.number) as number;
        break;
      case 'is_active':
        data.is_active = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'verification_code':
        data.verification_code = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as TrainingSessionsModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for VideoId fields
 */
function createIndexVideoId(
  video_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, video_id, 'video_id'),
  ];

  return {
    fields: ['video_id'],
    values
  };
}

export default TrainingSessionsORM;