// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: questions.
// - Entity ID: 102019b89b12756711eb339949f573585da.
// - Entity Version: 102019b8b5a5c89707ba4faf28a57fbb8d2.
// - Task ID: 695af84d032b09907ce19394.
// - Task Root ID: 695a8ab93c0e72020feb5a35.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for QuestionsModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface QuestionsModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  video_id: string;
  text: string;
  ideal_answer: string;
  sequence_number: number;
}

/**
 * ORM class for Questions entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class QuestionsORM {
  private static instance: QuestionsORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b89b12756711eb339949f573585da';
    this.entityName = 'questions';
    this.entityVersion = '102019b8b5a5c89707ba4faf28a57fbb8d2';
    this.taskId = '695af84d032b09907ce19394';
    this.taskRootId = '695a8ab93c0e72020feb5a35';
  }

  /**
   * Get singleton instance of QuestionsORM
   */
  public static getInstance(): QuestionsORM {
    if (!QuestionsORM.instance) {
      QuestionsORM.instance = new QuestionsORM();
    }
    
    return QuestionsORM.instance;
  }

  /**
   * Get questions by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getQuestionsByIDs(ids: string[]): Promise<QuestionsModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete questions by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteQuestionsByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Questions records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllQuestions(): Promise<QuestionsModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Questions record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertQuestions(data: QuestionsModel[]): Promise<QuestionsModel[]> {
    const structured = data.map((item) => CreateData(QuestionsModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Questions records
   */
  async purgeAllQuestions(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Questions records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listQuestions(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[QuestionsModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get questions by Id index
   * This function gets data by index.
   */
  async getQuestionsById(
    id: string,
  ): Promise<QuestionsModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) questions by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuestionsById(
    id: string,
    data: QuestionsModel
  ): Promise<QuestionsModel[]> {
    const index = createIndexId(
      id
    );

    const values = QuestionsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete questions by Id index
   */
  async deleteQuestionsById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get questions by DataCreator index
   * This function gets data by index.
   */
  async getQuestionsByDataCreator(
    data_creator: string,
  ): Promise<QuestionsModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) questions by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuestionsByDataCreator(
    data_creator: string,
    data: QuestionsModel
  ): Promise<QuestionsModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = QuestionsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete questions by DataCreator index
   */
  async deleteQuestionsByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get questions by DataUpdater index
   * This function gets data by index.
   */
  async getQuestionsByDataUpdater(
    data_updater: string,
  ): Promise<QuestionsModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) questions by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuestionsByDataUpdater(
    data_updater: string,
    data: QuestionsModel
  ): Promise<QuestionsModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = QuestionsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete questions by DataUpdater index
   */
  async deleteQuestionsByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get questions by VideoId index
   * This function gets data by index.
   */
  async getQuestionsByVideoId(
    video_id: string,
  ): Promise<QuestionsModel[]> {
    const index = createIndexVideoId(
      video_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) questions by VideoId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuestionsByVideoId(
    video_id: string,
    data: QuestionsModel
  ): Promise<QuestionsModel[]> {
    const index = createIndexVideoId(
      video_id
    );

    const values = QuestionsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete questions by VideoId index
   */
  async deleteQuestionsByVideoId(
    video_id: string
  ): Promise<void> {
    const index = createIndexVideoId(
      video_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get questions by SequenceNumberVideoId index
   * This function gets data by index.
   */
  async getQuestionsBySequenceNumberVideoId(
    sequence_number: number,
    video_id: string,
  ): Promise<QuestionsModel[]> {
    const index = createIndexSequenceNumberVideoId(
      sequence_number,
      video_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) questions by SequenceNumberVideoId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuestionsBySequenceNumberVideoId(
    sequence_number: number,
    video_id: string,
    data: QuestionsModel
  ): Promise<QuestionsModel[]> {
    const index = createIndexSequenceNumberVideoId(
      sequence_number,
      video_id
    );

    const values = QuestionsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete questions by SequenceNumberVideoId index
   */
  async deleteQuestionsBySequenceNumberVideoId(
    sequence_number: number,
    video_id: string
  ): Promise<void> {
    const index = createIndexSequenceNumberVideoId(
      sequence_number,
      video_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to QuestionsModel data array
   */
  private resultToData(values: Data[]): QuestionsModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return QuestionsModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as QuestionsModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized QuestionsModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is QuestionsModel => item !== null);
  }
}

/**
 * Convert QuestionsModel data to Value array
 */
function QuestionsModelToValues(data: QuestionsModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'video_id', type: DataType.string, defaultValue: '' },
    { key: 'text', type: DataType.string, defaultValue: '' },
    { key: 'ideal_answer', type: DataType.string, defaultValue: '' },
    { key: 'sequence_number', type: DataType.number, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof QuestionsModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to QuestionsModel data
 */
function QuestionsModelFromValues(values: Value[]): QuestionsModel {
  const data: Partial<QuestionsModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'video_id':
        data.video_id = ParseValue(value, DataType.string) as string;
        break;
      case 'text':
        data.text = ParseValue(value, DataType.string) as string;
        break;
      case 'ideal_answer':
        data.ideal_answer = ParseValue(value, DataType.string) as string;
        break;
      case 'sequence_number':
        data.sequence_number = ParseValue(value, DataType.number) as number;
        break;
    }
  }
  
  return data as QuestionsModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for VideoId fields
 */
function createIndexVideoId(
  video_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, video_id, 'video_id'),
  ];

  return {
    fields: ['video_id'],
    values
  };
}
/**
 * Create index for SequenceNumberVideoId fields
 */
function createIndexSequenceNumberVideoId(
  sequence_number: number,
  video_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.number, sequence_number, 'sequence_number'),
    CreateValue(DataType.string, video_id, 'video_id'),
  ];

  return {
    fields: ['sequence_number', 'video_id'],
    values
  };
}

export default QuestionsORM;