// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: user_progress.
// - Entity ID: 102019b89b1275674c29dab47ee0e8a4d59.
// - Entity Version: 102019b8b5a5c89707ba4faf28a57fbb8d2.
// - Task ID: 695af84d032b09907ce19394.
// - Task Root ID: 695a8ab93c0e72020feb5a35.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for UserProgressModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface UserProgressModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  video_id: string;
  is_completed: boolean;
  current_timestamp_watched?: number | null;
  completed_at?: string | null;
}

/**
 * ORM class for UserProgress entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class UserProgressORM {
  private static instance: UserProgressORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b89b1275674c29dab47ee0e8a4d59';
    this.entityName = 'user_progress';
    this.entityVersion = '102019b8b5a5c89707ba4faf28a57fbb8d2';
    this.taskId = '695af84d032b09907ce19394';
    this.taskRootId = '695a8ab93c0e72020feb5a35';
  }

  /**
   * Get singleton instance of UserProgressORM
   */
  public static getInstance(): UserProgressORM {
    if (!UserProgressORM.instance) {
      UserProgressORM.instance = new UserProgressORM();
    }
    
    return UserProgressORM.instance;
  }

  /**
   * Get user_progress by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getUserProgressByIDs(ids: string[]): Promise<UserProgressModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_progress by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteUserProgressByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all UserProgress records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllUserProgress(): Promise<UserProgressModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new UserProgress record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertUserProgress(data: UserProgressModel[]): Promise<UserProgressModel[]> {
    const structured = data.map((item) => CreateData(UserProgressModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all UserProgress records
   */
  async purgeAllUserProgress(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List UserProgress records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listUserProgress(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[UserProgressModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get user_progress by Id index
   * This function gets data by index.
   */
  async getUserProgressById(
    id: string,
  ): Promise<UserProgressModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_progress by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProgressById(
    id: string,
    data: UserProgressModel
  ): Promise<UserProgressModel[]> {
    const index = createIndexId(
      id
    );

    const values = UserProgressModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_progress by Id index
   */
  async deleteUserProgressById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_progress by DataCreator index
   * This function gets data by index.
   */
  async getUserProgressByDataCreator(
    data_creator: string,
  ): Promise<UserProgressModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_progress by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProgressByDataCreator(
    data_creator: string,
    data: UserProgressModel
  ): Promise<UserProgressModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = UserProgressModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_progress by DataCreator index
   */
  async deleteUserProgressByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_progress by DataUpdater index
   * This function gets data by index.
   */
  async getUserProgressByDataUpdater(
    data_updater: string,
  ): Promise<UserProgressModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_progress by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProgressByDataUpdater(
    data_updater: string,
    data: UserProgressModel
  ): Promise<UserProgressModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = UserProgressModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_progress by DataUpdater index
   */
  async deleteUserProgressByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_progress by UserId index
   * This function gets data by index.
   */
  async getUserProgressByUserId(
    user_id: string,
  ): Promise<UserProgressModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_progress by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProgressByUserId(
    user_id: string,
    data: UserProgressModel
  ): Promise<UserProgressModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = UserProgressModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_progress by UserId index
   */
  async deleteUserProgressByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_progress by VideoId index
   * This function gets data by index.
   */
  async getUserProgressByVideoId(
    video_id: string,
  ): Promise<UserProgressModel[]> {
    const index = createIndexVideoId(
      video_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_progress by VideoId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProgressByVideoId(
    video_id: string,
    data: UserProgressModel
  ): Promise<UserProgressModel[]> {
    const index = createIndexVideoId(
      video_id
    );

    const values = UserProgressModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_progress by VideoId index
   */
  async deleteUserProgressByVideoId(
    video_id: string
  ): Promise<void> {
    const index = createIndexVideoId(
      video_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_progress by UserIdVideoId index
   * This function gets data by index.
   */
  async getUserProgressByUserIdVideoId(
    user_id: string,
    video_id: string,
  ): Promise<UserProgressModel[]> {
    const index = createIndexUserIdVideoId(
      user_id,
      video_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_progress by UserIdVideoId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProgressByUserIdVideoId(
    user_id: string,
    video_id: string,
    data: UserProgressModel
  ): Promise<UserProgressModel[]> {
    const index = createIndexUserIdVideoId(
      user_id,
      video_id
    );

    const values = UserProgressModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_progress by UserIdVideoId index
   */
  async deleteUserProgressByUserIdVideoId(
    user_id: string,
    video_id: string
  ): Promise<void> {
    const index = createIndexUserIdVideoId(
      user_id,
      video_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to UserProgressModel data array
   */
  private resultToData(values: Data[]): UserProgressModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return UserProgressModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as UserProgressModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized UserProgressModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is UserProgressModel => item !== null);
  }
}

/**
 * Convert UserProgressModel data to Value array
 */
function UserProgressModelToValues(data: UserProgressModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'video_id', type: DataType.string, defaultValue: '' },
    { key: 'is_completed', type: DataType.boolean, defaultValue: false },
    { key: 'current_timestamp_watched', type: DataType.number, defaultValue: null },
    { key: 'completed_at', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof UserProgressModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to UserProgressModel data
 */
function UserProgressModelFromValues(values: Value[]): UserProgressModel {
  const data: Partial<UserProgressModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'video_id':
        data.video_id = ParseValue(value, DataType.string) as string;
        break;
      case 'is_completed':
        data.is_completed = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'current_timestamp_watched':
        data.current_timestamp_watched = ParseValue(value, DataType.number) as number | null;
        break;
      case 'completed_at':
        data.completed_at = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as UserProgressModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for VideoId fields
 */
function createIndexVideoId(
  video_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, video_id, 'video_id'),
  ];

  return {
    fields: ['video_id'],
    values
  };
}
/**
 * Create index for UserIdVideoId fields
 */
function createIndexUserIdVideoId(
  user_id: string,
  video_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
    CreateValue(DataType.string, video_id, 'video_id'),
  ];

  return {
    fields: ['user_id', 'video_id'],
    values
  };
}

export default UserProgressORM;