// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: completions.
// - Entity ID: 102019b89b1275678df97a73789c5c47899.
// - Entity Version: 102019b8b5a5c89707ba4faf28a57fbb8d2.
// - Task ID: 695af84d032b09907ce19394.
// - Task Root ID: 695a8ab93c0e72020feb5a35.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for CompletionsModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface CompletionsModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  video_id: string;
  completion_code: string;
  score: number;
  completed_at: string;
}

/**
 * ORM class for Completions entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class CompletionsORM {
  private static instance: CompletionsORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b89b1275678df97a73789c5c47899';
    this.entityName = 'completions';
    this.entityVersion = '102019b8b5a5c89707ba4faf28a57fbb8d2';
    this.taskId = '695af84d032b09907ce19394';
    this.taskRootId = '695a8ab93c0e72020feb5a35';
  }

  /**
   * Get singleton instance of CompletionsORM
   */
  public static getInstance(): CompletionsORM {
    if (!CompletionsORM.instance) {
      CompletionsORM.instance = new CompletionsORM();
    }
    
    return CompletionsORM.instance;
  }

  /**
   * Get completions by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getCompletionsByIDs(ids: string[]): Promise<CompletionsModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete completions by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteCompletionsByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Completions records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllCompletions(): Promise<CompletionsModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Completions record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertCompletions(data: CompletionsModel[]): Promise<CompletionsModel[]> {
    const structured = data.map((item) => CreateData(CompletionsModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Completions records
   */
  async purgeAllCompletions(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Completions records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listCompletions(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[CompletionsModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get completions by Id index
   * This function gets data by index.
   */
  async getCompletionsById(
    id: string,
  ): Promise<CompletionsModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) completions by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCompletionsById(
    id: string,
    data: CompletionsModel
  ): Promise<CompletionsModel[]> {
    const index = createIndexId(
      id
    );

    const values = CompletionsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete completions by Id index
   */
  async deleteCompletionsById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get completions by DataCreator index
   * This function gets data by index.
   */
  async getCompletionsByDataCreator(
    data_creator: string,
  ): Promise<CompletionsModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) completions by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCompletionsByDataCreator(
    data_creator: string,
    data: CompletionsModel
  ): Promise<CompletionsModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = CompletionsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete completions by DataCreator index
   */
  async deleteCompletionsByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get completions by DataUpdater index
   * This function gets data by index.
   */
  async getCompletionsByDataUpdater(
    data_updater: string,
  ): Promise<CompletionsModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) completions by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCompletionsByDataUpdater(
    data_updater: string,
    data: CompletionsModel
  ): Promise<CompletionsModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = CompletionsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete completions by DataUpdater index
   */
  async deleteCompletionsByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get completions by UserId index
   * This function gets data by index.
   */
  async getCompletionsByUserId(
    user_id: string,
  ): Promise<CompletionsModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) completions by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCompletionsByUserId(
    user_id: string,
    data: CompletionsModel
  ): Promise<CompletionsModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = CompletionsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete completions by UserId index
   */
  async deleteCompletionsByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get completions by VideoId index
   * This function gets data by index.
   */
  async getCompletionsByVideoId(
    video_id: string,
  ): Promise<CompletionsModel[]> {
    const index = createIndexVideoId(
      video_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) completions by VideoId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCompletionsByVideoId(
    video_id: string,
    data: CompletionsModel
  ): Promise<CompletionsModel[]> {
    const index = createIndexVideoId(
      video_id
    );

    const values = CompletionsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete completions by VideoId index
   */
  async deleteCompletionsByVideoId(
    video_id: string
  ): Promise<void> {
    const index = createIndexVideoId(
      video_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get completions by CompletionCode index
   * This function gets data by index.
   */
  async getCompletionsByCompletionCode(
    completion_code: string,
  ): Promise<CompletionsModel[]> {
    const index = createIndexCompletionCode(
      completion_code
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) completions by CompletionCode index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCompletionsByCompletionCode(
    completion_code: string,
    data: CompletionsModel
  ): Promise<CompletionsModel[]> {
    const index = createIndexCompletionCode(
      completion_code
    );

    const values = CompletionsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete completions by CompletionCode index
   */
  async deleteCompletionsByCompletionCode(
    completion_code: string
  ): Promise<void> {
    const index = createIndexCompletionCode(
      completion_code
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to CompletionsModel data array
   */
  private resultToData(values: Data[]): CompletionsModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return CompletionsModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as CompletionsModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized CompletionsModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is CompletionsModel => item !== null);
  }
}

/**
 * Convert CompletionsModel data to Value array
 */
function CompletionsModelToValues(data: CompletionsModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'video_id', type: DataType.string, defaultValue: '' },
    { key: 'completion_code', type: DataType.string, defaultValue: '' },
    { key: 'score', type: DataType.number, defaultValue: 0 },
    { key: 'completed_at', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof CompletionsModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to CompletionsModel data
 */
function CompletionsModelFromValues(values: Value[]): CompletionsModel {
  const data: Partial<CompletionsModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'video_id':
        data.video_id = ParseValue(value, DataType.string) as string;
        break;
      case 'completion_code':
        data.completion_code = ParseValue(value, DataType.string) as string;
        break;
      case 'score':
        data.score = ParseValue(value, DataType.number) as number;
        break;
      case 'completed_at':
        data.completed_at = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as CompletionsModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for VideoId fields
 */
function createIndexVideoId(
  video_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, video_id, 'video_id'),
  ];

  return {
    fields: ['video_id'],
    values
  };
}
/**
 * Create index for CompletionCode fields
 */
function createIndexCompletionCode(
  completion_code: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, completion_code, 'completion_code'),
  ];

  return {
    fields: ['completion_code'],
    values
  };
}

export default CompletionsORM;